"""Initial migration creating core tables.

Revision ID: 20260824_initial
Revises: 
Create Date: 2026-08-24 00:00:00.000000
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20260824_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create all core tables for RedPulse database."""

    # ### commands auto-generated by Alembic revision 20260824_initial ###
    # These commands create the base tables based on the SQLAlchemy models:

    # CREATE TABLE users
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)

    # CREATE TABLE projects
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=True)

    # CREATE TABLE engagements
    op.create_table(
        "engagements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_engagements_id"), "engagements", ["id"], unique=True)

    # CREATE TABLE authorizations
    op.create_table(
        "authorizations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("engagement_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("target_domain", sa.String(length=255), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("verification_token", sa.String(length=500), nullable=True),
        sa.Column("bounty_platform", sa.String(length=100), nullable=True),
        sa.Column("bounty_program_handle", sa.String(length=255), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("engagement_id"),
    )
    op.create_index(op.f("ix_authorizations_id"), "authorizations", ["id"], unique=True)

    # CREATE TABLE platform_connections
    op.create_table(
        "platform_connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("access_token", sa.String(length=500), nullable=False),
        sa.Column("platform_username", sa.String(length=255), nullable=True),
        sa.Column("connected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_platform_connections_id"), "platform_connections", ["id"], unique=True)

    # CREATE TABLE scope_rules
    op.create_table(
        "scope_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("engagement_id", sa.String(length=36), nullable=False),
        sa.Column("pattern", sa.String(length=255), nullable=False),
        sa.Column("rule_type", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scope_rules_id"), "scope_rules", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop all core tables."""

    # ### commands auto-generated by Alembic revision 20260824_initial ###
    op.drop_table("platform_connections")
    op.drop_table("scope_rules")
    op.drop_table("authorizations")
    op.drop_table("engagements")
    op.drop_table("projects")
    op.drop_table("users")
    # ### end Alembic commands ###